name: Digital Flow

on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Update and upgrade system
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Install required packages
      run: |
        sudo apt install -y build-essential python3 python3-venv python3-pip python3-tk curl make git docker.io

    - name: Verify Docker and Python installations
      run: |
        docker --version
        python3 --version
        python3 -m pip --version

    - name: Install OpenLane
      run: python3 -m pip install openlane

    - name: Run Test
      run: |
        python3 -m openlane --docker-no-tty --dockerized --smoke-test

    - name: Run OpenLane
      run: |
        cd my_project
        python3 -m openlane --docker-no-tty --dockerized --flow Classic config.json

