name: Digital Flow

on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Update and upgrade system
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Install required packages
      run: |
        sudo apt install -y build-essential python3 python3-venv python3-pip python3-tk curl make git docker.io

    - name: Verify Docker and Python installations
      run: |
        docker --version
        python3 --version
        python3 -m pip --version

    - name: Install OpenLane
      run: python3 -m pip install openlane

    - name: Run OpenLane
      run: |
        cd my_project
        python3 -m openlane --docker-no-tty --dockerized --flow Classic config.json

    - name: Find and Upload GDS file
      run: |
        # Last run is saved
        LAST_RUN_DIR=$(ls -d my_project/runs/RUN_* | sort | tail -n 1)
        GDS_FILE="$LAST_RUN_DIR/final/gds/my_project.gds"

        if [ -f "$GDS_FILE" ]; then
          echo "GDS file found at: $GDS_FILE"
          echo "gds_path=$GDS_FILE" >> $GITHUB_ENV
        else
          echo "Error: No GDS file found in the latest run directory!"
          exit 1
        fi

    - name: Upload GDS file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: myproject-gds
        path: ${{ env.gds_path }}

  gds-viewer:
    runs-on: ubuntu-20.04  # Configuración para Ubuntu 20.04
    needs: install-and-test  # Asegura que el paso anterior se haya completado

    steps:
    - name: Check out 3DGDS-in-Action repository
      uses: actions/checkout@v4
      with:
        repository: Gior-gio/3DGDS-in-Action
        path: gds-viewer 

    - name: Download GDS file artifact
      uses: actions/download-artifact@v4
      with:
        name: myproject-gds
        path: './'  

    - name: Replace existing .gds file
      run: |
        rm ./gds-viewer/*.gds  
        cp mcdy_project.gds ./gds-viewer 

    - name: Visualize GDS file
      uses: Gior-gio/gds-viewer/flow